spring.application.name=Spring_MICROSERVICES_product_service
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/micro_product_db
spring.datasource.username=root
spring.datasource.password=Pikachu@22
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true